compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
 gradient_clipping: 1.0
 offload_optimizer_device: cpu
 offload_param_device: cpu
 zero_stage: 2
distributed_type: DEEPSPEED
gpu_ids: all
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false